### ISSUE TITLE
Dinoksetiid xEdit Concerns

### ISSUE THREAD

**Issue by DerrylHopkins** [Geborgen/dinoksetiid#1]
While poking around the list in xEdit, I found some things I wanted to bring to your attention:

Unofficial Expanded Crossbow Pack Patch.esl introduces the SilverSwordScript to the Silver Crossbow (FormID FE00780E) and the Enhanced Silver Crossbow (FormID FE00781A), but this change is ultimately overwritten by Kachunk - Crossbow Distribution. This may be an intended balancing overwrite due to the high number of undead enemies encountered within Dinoksetiid, of course, but I thought it was worth mentioning.

Quite a few of Unofficial Skyrim Special Edition Patch.esp’s changes to XLCN - Location and XCWT - Water record properties are not forwarded in the finalized Occlusion.esp or DynDOLOD.esp. FormIDs include 000090CF, 000090D0, 00009292, 00009349, 000095E6, 00009636, 0000972A, 0000979F, 000097A0, 0000B499, 0000B4B8, 0000B4BA, 0000B4BB, 0000BCD5, 0000BCDA, 00020EE7, 0001A275, 0001A276, 0000B4DB, 0000B4DC, 000095CF, 00009AE1, and 00009B02.

Evenstar - Minimalistic Standing Stones of Skyrim.esp’s changes to the effects of The Steed Stone (FormID 000E5F5E) are completely overwritten by SurvivalModeImproved.esp. Loading Evenstar after SMI will fix this and prevent other issues from arising, according to SMI’s mod page: “Mundus - A Standing Stone Overhaul (or other standing stone mods) - Please make sure these mods load AFTER SMI.”

1Daedra.esp completely overwrites a couple of vendor container records that are established or changed by mods such as MysticismMagic.esp and mihailshambles.esp. FormIDs include 00078C0C and 00098BA2.

Thaumaturgy.esp’s changes to a small number of Nord-related enchanted weapons are overwritten by The Restless.esp. FormIDs include 0005BF06, 0005BF07, 0005BF08, 000DDD64, 000DDD65, and 000DDD66. These are just FULL - Name record properties, but if you want consistency in the names of all enchanted weapons, you will want to forward them.

Stormcrown.esp’s changes to the Dragonrend Shout (FormIDs 00028315, 00028345, and 00044254) are overwritten by DeadlyDragons.esp. I believe just loading the former after the latter should work, but you may want to ensure that the dragons added by Deadly Dragons cannot then absorb and/or resist the Shout. If they can, you will want to forward the Ignore Resistance and No Absorb/Reflect Flags.

Pilgrim.esp adds Persistent Flags to various NPCs that are ultimately overwritten by Alternate Skyrim.esp. FormIDs include 000198A5, 000198A6, 000198A7, 000585FC, and 0001E766. I highly recommend forwarding these Flags.

Gourmet.esp adds a Persistent Flag to an NPC that is ultimately overwritten by Alternate Skyrim.esp. It has the FormID 001027DB. I highly recommend forwarding this Flag.

Gourmet.esp’s changes to a plethora of Ingestible records are ultimately overwritten by SurvivalModeImproved.esp. Load Gourmet.esp, GourmetSurvival.esp and GourmetFishing.esp after SurvivalModeImproved.esp as is suggested by the latter’s mod page’s compatibility section: “Any other Simonrim mod - Just let said mod overwrite SMI's changes.”

Humanoid Dragon Priest.esp’s changes to Morokei (FormID 000F496C) are ultimately overwritten by Alternate Skyrim.esp.

Clockwork.esp has a lot of conflicting Navmesh records with other mods. FormIDs include 00106500, 00100F4B, 0001689A, 00105E9F, 000DEEF0, 000E808A, 000A8243, 000CB24E, 00103740, 00103741, 0008A000, 00042D1C, 000EC47B, 00105917, 00105918, 000EC469, 000FC11C, 000FC127, 000A17CC, 000E0BCB, and 000E0BC4.

Some of ClockworkBugFixes.esp’s changes are reverted rather than forwarded by other mods. FormIDs include 22024059, 2202405C, 2202D718, 2202D719, 2202DC7E, 2202DC7F, 22093DCA, 22093DCB, 22093DCC, 22093DCD, and 22093DDD.

1Minotaurs.esp has a Navmesh record conflict with AncientLand2.esp at FormID 000EC46D.

1Ogres.esp has Navmesh conflicts with other mods at FormIDs 00101A9A, 000FD724, 00101A86, and 000FD725.

Ryn’s Dragon Mounds AIO.esp has Navmesh conflicts with other mods at FormIDs 000F8B9A, 000F8B97, 0004C072, 00101B94, 00101BC4, 00101BC5, 00101BC6, 00101BC7, 00101BC8, 00101BC9, and 00101BCA.

 AncientLand2.esp has Navmesh conflicts with AnotherOakwood.esp at FormIDs 000F25EA and 000F25ED. It also has one with JUSTICE - City Exteriors.esp at FormID 000FC11F.

Alternate Skyrim.esp removes the Can’t Fast Travel Flag from the Japhet’s Folly Worldspace (FormID 00094B35), but FWMF for Fantasy Paper Maps.esp ultimately reintroduces it.

If I find anything else, I'll let you know! :D

**Comment by Geborgen** [comment]
Damn you came in and fixed my cluttered load order. This is why version 1.0 on a solo dev project is fun, focusing too much on certain aspects and neglecting obvious other things. I appreciate the report :)
