### ISSUE TITLE
[BUG] Purple World Map

### ISSUE THREAD

**Issue by Watson203** [Geborgen/dinoksetiid#6]
**Describe The Bug**
World Map has a purple overlay when viewed normally.

**Expected Behavior**
I should be able to see the world map.

**Send Your Crash Log**
no crash log

**Screenshots**
![Screenshot 2024-12-11 195929](https://github.com/user-attachments/assets/bb68c134-7ecb-4b4f-bb7b-48979238f0ce)

**List Version**
v1.0.1

**Additional Context**
I can see the world map briefly as it zooms out, but is then replaced with a purple screen

**Comment by Geborgen** [comment]
Youve placed plugins below the map plugins. Please do not submit bug reports with a modified list.
